apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freelancer-manager
  namespace: freelancer-manager-dev
spec:
  ingressClassName: traefik
  rules:
    - host: api.codeborges.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-api
                port:
                  number: 80
    - host: app.codeborges.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-web
                port:
                  number: 80
