apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-secret.yaml
  - ingress.yaml
  - namespace.yaml
  - saas-api-deployment.yaml
  - saas-api-hpa.yaml
  - saas-api-migration-job.yaml
  - saas-api-secret.yaml
  - saas-api-service.yaml
  - saas-web-deployment.yaml
  - saas-web-hpa.yaml
  - saas-web-secret.yaml
  - saas-web-service.yaml
images:
  - name: ghcr.io/gabrielborges2000/freelancer-manager-backend-dev
    newTag: latest

  - name: ghcr.io/gabrielborges2000/freelancer-manager-frontend-dev
    newTag: latest
