apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - saas-api-deployment.yaml
  - saas-api-migration-job.yaml
  - saas-web-deployment.yaml
images:
  - name: ghcr.io/GabrielBorges2000/freelancer-manager-backend-dev
    newTag: sha-123456
    digest: sha256:null
  - name: ghcr.io/GabrielBorges2000/freelancer-manager-frontend-dev
    newTag: sha-abcdef
    digest: sha256:null
