# Token do tunnel: Cloudflare Zero Trust > Access > Tunnels > seu tunnel > Configure
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: cloudflare
type: Opaque
stringData:
  token: "eyJhIjoiMmQ0OGQ2OWYzN2IzYmQxNTJkYjI4ZDliYmRiODMyZmQiLCJ0IjoiYzg5NGExNTItNzc4Yi00OTZmLTlmOGEtY2UwNmQ5NTYwYzM0IiwicyI6Ik5tRTNZV0U1WW1JdE9URmhNaTAwTmpoakxXRm1NREl0TXpNd01qZzBOMkl4TUdReiJ9"
